services:
  app:
    env_file:
      - in-container.env
    build:
      context: ../../
      dockerfile: docker/base/Dockerfile
    ports:
      - "${HTTP_PORT:-8080}:80"
    volumes:
      - "../base/confs/php-fpm-app.conf:/usr/local/etc/php-fpm.d/php-fpm-app.conf:ro"
      - "../base/confs/php-app.ini:/usr/local/etc/php/conf.d/php-app:ro"
    depends_on:
      - db
      - redis
    networks:
      - default
      - db-internal
      - db-redis

  db:
    env_file:
      - in-container.env
    image: postgres
    networks:
      - db-internal

  redis:
    env_file:
      - in-container.env
    image: redis
    networks:
      - db-redis


networks:
  db-internal: {}
  db-redis: {}
