services:
  demo-app:
    extends:
      file: ../base/docker-compose-base.yml
      service: base-app
    build:
      target: "demo"
    container_name: "my-docker-app-demo"
    volumes:
      - "../../app:/app"
    env_file:
      - ../demo/in-container-app.env
    profiles:
      - demo
    depends_on:
      - demo-db
      - demo-valkey

  demo-db:
    extends:
      file: ../base/docker-compose-base.yml
      service: base-db
    container_name: "my-docker-db-demo"
    env_file:
      - ../demo/in-container-db.env
    profiles:
      - demo

  demo-valkey:
    extends:
      file: ../base/docker-compose-base.yml
      service: base-valkey
    container_name: "my-docker-valkey-demo"
    env_file:
      - ../demo/in-container-valkey.env
    profiles:
      - demo
