services:
  prod-app:
    extends:
      file: ../base/docker-compose-base.yml
      service: base-app
    build:
      target: "prod"
    container_name: "my-docker-app-prod"
    volumes:
      - "../../app:/app"
    env_file:
      - ../prod/in-container-app.env
    profiles:
      - prod
    depends_on:
      - prod-db
      - prod-valkey

  prod-db:
    extends:
      file: ../base/docker-compose-base.yml
      service: base-db
    container_name: "my-docker-db-prod"
    env_file:
      - ../prod/in-container-db.env
    profiles:
      - prod

  prod-valkey:
    extends:
      file: ../base/docker-compose-base.yml
      service: base-valkey
    container_name: "my-docker-valkey-prod"
    env_file:
      - ../prod/in-container-valkey.env
    profiles:
      - prod
